name: 'Build SafeWalk.Platform'
description: 'Builds the SafeWalk.Platform .NET solution'
inputs:
  dotnet-version:
    description: 'The .NET SDK version to use'
    required: false
    default: '9.0.x'
  configuration:
    description: 'Build configuration (Debug or Release)'
    required: false
    default: 'Release'
  solution-path:
    description: 'Path to the solution file'
    required: false
    default: 'SafeWalk.Platform/SafeWalk.Platform.sln'
outputs:
  build-status:
    description: 'Build status (success or failure)'
    value: ${{ steps.build.outputs.status }}
runs:
  using: 'composite'
  steps:
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ inputs.dotnet-version }}

    - name: Display .NET version
      shell: bash
      run: dotnet --version

    - name: Restore dependencies
      shell: bash
      run: |
        echo "Restoring NuGet packages for ${{ inputs.solution-path }}..."
        dotnet restore "${{ inputs.solution-path }}"

    - name: Build solution
      id: build
      shell: bash
      run: |
        echo "Building ${{ inputs.solution-path }} in ${{ inputs.configuration }} configuration..."
        if dotnet build "${{ inputs.solution-path }}" \
          --configuration ${{ inputs.configuration }} \
          --no-restore \
          --verbosity minimal; then
          echo "Build succeeded!"
          echo "status=success" >> $GITHUB_OUTPUT
        else
          echo "Build failed!"
          echo "status=failure" >> $GITHUB_OUTPUT
          exit 1
        fi

    - name: Build summary
      if: always()
      shell: bash
      run: |
        if [ "${{ steps.build.outputs.status }}" = "success" ]; then
          echo "### SafeWalk.Platform Build Successful" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Configuration:** ${{ inputs.configuration }}" >> $GITHUB_STEP_SUMMARY
          echo "**Solution:** ${{ inputs.solution-path }}" >> $GITHUB_STEP_SUMMARY
          echo "**.NET Version:** ${{ inputs.dotnet-version }}" >> $GITHUB_STEP_SUMMARY
        else
          echo "### SafeWalk.Platform Build Failed" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Configuration:** ${{ inputs.configuration }}" >> $GITHUB_STEP_SUMMARY
          echo "**Solution:** ${{ inputs.solution-path }}" >> $GITHUB_STEP_SUMMARY
          echo "**.NET Version:** ${{ inputs.dotnet-version }}" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "Please check the build logs above for details." >> $GITHUB_STEP_SUMMARY
        fi
